# Generated by Django 2.2.4 on 2021-03-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_creator_app', '0003_auto_20210304_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
