# Generated by Django 2.2.4 on 2021-03-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_creator_app', '0004_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='move',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='favorited_users',
        ),
        migrations.RemoveField(
            model_name='type',
            name='pokemon',
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
